/*
 * Code-Notes | TabHeader.java
 * Created | 11:38:20 PM Oct 10, 2019
 */
package code.notes.gui;

import code.notes.Bundle;

/**
 *
 * @author phwts
 */
public class TabHeader extends javax.swing.JPanel {
    private final int tabID;
    private final TextEditor editor;
    /**
     * Creates new form TabHeader
     */
    public TabHeader(TextEditor editor, int tabID) {
        initComponents();
        this.editor = editor;
        this.tabID = tabID;
        labelFileName.setText(Bundle.get("new_file"));
    }

    public TabHeader(TextEditor editor, int tabID, String filename) {
        initComponents();
        this.editor = editor;
        this.tabID = tabID;
        labelFileName.setText(filename);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFileName = new javax.swing.JLabel();
        btnCloseTab = new javax.swing.JLabel();

        setOpaque(false);

        labelFileName.setText("File Name");

        btnCloseTab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCloseTab.setText("X");
        btnCloseTab.setAlignmentY(0.0F);
        btnCloseTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCloseTab.setIconTextGap(0);
        btnCloseTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCloseTabMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelFileName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCloseTab)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelFileName)
                .addComponent(btnCloseTab))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseTabMousePressed
        editor.getEditorPane().removeTabAt(tabID);
    }//GEN-LAST:event_btnCloseTabMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCloseTab;
    private javax.swing.JLabel labelFileName;
    // End of variables declaration//GEN-END:variables
}
