/* 
 * Code-Notes | TextEditor.java
 * Created | 1:29:02 PM ‎Oct ‎10, ‎2019
 */
package code.notes.gui;

import code.notes.Bundle;
import code.notes.util.FileChooser;
import code.notes.util.FileHandler;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author phwts
 */
public class TextEditor extends javax.swing.JFrame {

    public static int newfile_count = 0;

    /**
     * Creates new form TextEditor
     */
    public TextEditor() {
        initComponents();
        addEmptyTab();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editorPane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuOpen = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuSaveAs = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuCloseTab = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("code/notes/Bundle"); // NOI18N
        setTitle(bundle.getString("title")); // NOI18N
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(500, 300));
        setPreferredSize(new java.awt.Dimension(750, 500));

        editorPane.setToolTipText("");
        editorPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editorPane.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                editorPaneComponentAdded(evt);
            }
        });

        jTree1.setEnabled(false);
        jScrollPane1.setViewportView(jTree1);

        jMenu1.setText("File");

        menuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuOpen.setText(bundle.getString("open")); // NOI18N
        menuOpen.setActionCommand(bundle.getString("open")); // NOI18N
        menuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpenActionPerformed(evt);
            }
        });
        jMenu1.add(menuOpen);

        menuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSave.setText(bundle.getString("save")); // NOI18N
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        jMenu1.add(menuSave);

        menuSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuSaveAs.setText(bundle.getString("save_as")); // NOI18N
        menuSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveAsActionPerformed(evt);
            }
        });
        jMenu1.add(menuSaveAs);
        jMenu1.add(jSeparator2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText(bundle.getString("new_file")); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menuCloseTab.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        menuCloseTab.setText(bundle.getString("close_file")); // NOI18N
        menuCloseTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCloseTabActionPerformed(evt);
            }
        });
        jMenu1.add(menuCloseTab);

        jMenuBar1.add(jMenu1);

        jMenu2.setText(bundle.getString("tools")); // NOI18N

        jMenuItem2.setText(bundle.getString("exception_lookup")); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Preferences");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editorPane, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
            .addComponent(editorPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public SingleEditor getCurrentEditor() {
        return (SingleEditor) editorPane.getSelectedComponent();
    }

    private void menuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenActionPerformed
        File[] paths = FileChooser.openFiles();
        if (paths == null) {
            return;
        }
        for (File file : paths) {
            addNewTab(file.getAbsolutePath());
        }
    }//GEN-LAST:event_menuOpenActionPerformed

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed
        SingleEditor singleEditor = getCurrentEditor();
        singleEditor.saveTrue();
        String currentText = singleEditor.getTextArea().getText();
        if (singleEditor.getPath().isEmpty()) {
            menuSaveAsActionPerformed(evt);
            return;
        }
        FileHandler.save(singleEditor.getPath(), currentText);
    }//GEN-LAST:event_menuSaveActionPerformed

    private void menuSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveAsActionPerformed
        SingleEditor singleEditor = getCurrentEditor();
        int index = editorPane.indexOfTab(singleEditor.getFileName());
        String path = FileChooser.save(singleEditor.getFileName());

        if (path == null) {
            return;
        }
        
        String currentText = singleEditor.getTextArea().getText();

        FileHandler.save(path, currentText);
        singleEditor.setContent(currentText);

        singleEditor.setPath(path);
        
        singleEditor.saveTrue();
        ((TabHeader) editorPane.getTabComponentAt(index)).setFilename(path, true);
        getCurrentEditor().setExtension();
    }//GEN-LAST:event_menuSaveAsActionPerformed

    private void addNewTab(String path) {
        SingleEditor singleEditor = new SingleEditor(this, path);

        String filename = singleEditor.getFileName();

        int index = editorPane.indexOfTab(filename);
        if (index != -1) {
            editorPane.setSelectedIndex(index);
            return;
        }

        editorPane.addTab(filename, singleEditor);
        index = editorPane.indexOfTab(filename);
        editorPane.setTabComponentAt(index, new TabHeader(this, filename));
    }

    private void addEmptyTab() {
        newfile_count++;
        SingleEditor singleEditor = new SingleEditor(this);

        editorPane.addTab(singleEditor.getFileName(), singleEditor);

        int index = editorPane.indexOfTab(singleEditor.getFileName());
        editorPane.setTabComponentAt(index, new TabHeader(this, "New File " + newfile_count));
    }

    public void updateHeader(String filename, boolean saved) {
        int index = editorPane.indexOfTab(filename);
        ((TabHeader) editorPane.getTabComponentAt(index)).setFilename(filename, saved);
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        addEmptyTab();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuCloseTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCloseTabActionPerformed
        closeTabAt(getCurrentEditor().getFileName());
    }//GEN-LAST:event_menuCloseTabActionPerformed

    private void editorPaneComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_editorPaneComponentAdded
        editorPane.setSelectedIndex(editorPane.getTabCount() - 1);
    }//GEN-LAST:event_editorPaneComponentAdded

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new ExceptionForm().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new SettingsForm().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    public void closeTabAt(String filename) {
        
        try {
            int index = editorPane.indexOfTab(filename);
            editorPane.removeTabAt(index);
        } catch (Exception ex) {
            editorPane.removeTabAt(editorPane.getTabCount() - 1);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane editorPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenuItem menuCloseTab;
    private javax.swing.JMenuItem menuOpen;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JMenuItem menuSaveAs;
    // End of variables declaration//GEN-END:variables

}
